### ISSUE TITLE
Update readme to reflect current status

### ISSUE THREAD

**Issue by RasmusWL** [EHVAG/demoinfo#85] opened 2016-01-19 13:58 UTC
I just worked on a little project with CS:GO demo files, and looked at the available projects. I read the readme for this project, which stated that a lot of events where still not implemented!

Instead I settled on https://github.com/mikeemoo/jsgo. But it seems this repo is in fact much more maintained, and has a lot more useful features to do the heavy lifting for you.

If you could update the readme to reflect the current status of the project, so other people don't make the same mistake as I did, that would be super fantastic :+1: !

**Comment by moritzuehling** [comment] 2016-01-19 16:12
Hi!

What changes would you like to see? You can also open a PR and fix this yourself.

**Comment by JSterling8** [comment] 2016-01-19 16:13
Yeah, I just looked at that other repo and demoinfo is leaps and bounds better.  I think the issue is the link to the TODO list in the README is outdated.  It links to this: https://gist.github.com/moritzuehling/bcc71f306249f0d85628

A lot of stuff on that is now implemented but marked as not implemented.

**Comment by RasmusWL** [comment] 2016-01-20 21:30
Excatly my point @JSterling8 !

**Comment by JSterling8** [comment] 2016-01-20 22:09
@RasmusWL - If you clone the repository you can edit the README file and update it?  I'm a bit too swamped with work at the minute to do it myself.

**Comment by RasmusWL** [comment] 2016-01-20 22:31
Usually I would, but as I never used this project I do not know what features are implemented and what are not. I simply wanted to let you guys know that users might be turned away by the old todo list showing many things are not working :cry: (like I was)

**Comment by JSterling8** [comment] 2016-01-21 14:02
@RasmusWL - https://github.com/EHVAG/demoinfo/pull/86.  Done.  No need to recreate a TODO list when users can see if what they need is in the features section.

**Comment by moritzuehling** [comment] 2016-01-21 14:52
Closed by #86.

**Closed by moritzuehling** 2016-01-21 14:52 UTC
